export const alpha3ToAlph2 = {
    'AFG': 'AF',
    'SRB': 'RS',
    'BLR': 'BY',
    'POL': 'PL',
    'ESP': 'ES',
    'RUS': 'RU',
    'USA': 'US',
    'DEN': 'DK',
    'KAZ': 'KZ',
    'GRE': 'GR',
    'CZE': 'CZ',
    'ITA': 'IT',
    'TUN': 'TN',
    'NOR': 'NO',
    'FRA': 'FR',
    'GER': 'DE',
    'AUS': 'AU',
    'CAN': 'CA',
    'SUI': 'SU',  // ???
    'GBR': 'GB',
    'BUL': 'BG',
    'BRA': 'BR',
    'ARG': 'AR',
    'CRO': 'HR',
    'CHI': 'CL',
    'CHN': 'CN',
    'NED': 'NL',
    'UKR': 'UA',
    'BEL': 'BE', // ??? Belarus OR Belgium OR Belize
    'EGY': 'EG',
    'SLO': 'SL', // Slovakia OR Slovenia
    'COL': 'CO',
    'POR': 'PT',
    'SWE': 'SE',
    'HUN': 'HU', ///
    'JPN': 'JP',
}